### ISSUE TITLE
link broken on video17

### ISSUE THREAD

**Issue by splaisan** [hpcleuven/HPC-intro#2]
Unless Jan is working on it, the fore last link seems also dead
Thanks for your support

// Worker framework | Optional | 18 min
https://kuleuven.mediaspace.kaltura.com/media/HPCIntro-17-worker/1_pz537i1i

**Comment by moravveji** [comment]
Hi. 

I can easily open the URL you posted (worker framework), and browse through the whole video.
 Maybe there was a temporal load on the Kaltura server. 

Can you please try to watch again?

**Comment by splaisan** [comment]
Same here today, thanks for your help :-)
Stephane
